services:
    twig.extension.photo:
        class: L3\Bundle\PhotoBundle\Photo
        arguments: ["%photo_image_url%","%photo_token_url%"]
        public: true
        tags:
            - { name: twig.extension }
